### PR TITLE
New lab instructions for ravello based lab environment

### PR DESCRIPTION
**Pull request by jbride**

### CODE REVIEW

**Comment by cmoulliard** [comment]
Question: Will this PR replace the PR22 ? If no, do you plan to submit a PR containing both ? @jbride

**Comment by jbride** [comment]
I've closed pull request #22 .
This is the pull request I'll continue to build upon as the lab evolves.

**Comment by cmoulliard** [comment]
Do you want that we merge it now ? @jbride

**Comment by jbride** [comment]
@cmoulliard :   yes, please

**Pull request merged**
